{% set version = "1.7.9" %}
{% set am_version = "1.15" %}

package:
  name: chktex
  version: {{ version }}

source:
  url: https://download.savannah.gnu.org/releases/chktex/chktex-{{ version }}.tar.gz
  sha256: df6ee31632a4f4a8e18849b804657e27e3d96deb3f237edbd25656415eb31195
  patches:
    - 000-makefile-no-dvi.patch
    - 001-makefile-no-less.patch
  # TODO: figure out how to get osx to use ncurses

build:
  number: 1
  missing_dso_whitelist:
    - /usr/lib/libncurses.5.4.dylib  # [osx]

requirements:
  build:
    - m2-autoconf                   # [win]
    - m2-automake{{ am_version }}   # [win]
    - m2-libtool                    # [win]
    - m2-patch                      # [win]
    - m2-sed                        # [win]
    - pkg-config              # [win]
    - m2-base                         # [win]
    - {{ compiler('m2w64_c') }}     # [win]
    - {{ compiler('c') }}           # [unix]
    - {{ stdlib("c") }}             # [unix]
    - autoconf                      # [unix]
    - automake                      # [unix]
    - gettext                       # [unix]
    - libtool                       # [unix]
    - make                          # [unix]
    - patch                         # [unix]
    - pkg-config                    # [unix]
    - sed                           # [unix]
  host:
    - ncurses                       # [unix]
    - m2-ncurses                    # [win]
    # TODO: probably want pcre, but keep segfaulting with 8.44
    # - pcre                        # [unix]
    # - m2-pcre                     # [win]
  run:
    - ncurses                       # [unix]
    - m2-ncurses                    # [win]
    # - pcre                        # [unix]
    # - m2-pcre                     # [win]

test:
  commands:
    - chktex --version
    # these are shell scripts... but don't appear to be needed for chktex to "work"
    - deweb --version  # [unix]
    - chkweb --version  # [unix]

about:
  home: https://www.nongnu.org/chktex
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LaTeX semantic checker
  description: |
    This program has been written in frustration because some constructs in
    LaTeX are sometimes non-intuitive, and easy to forget. It is _not_ a
    replacement for the built-in checker in LaTeX; however it catches some
    typographic errors LaTeX oversees. In other words, it is Lint for LaTeX.
    Filters are also provided for checking the LaTeX parts of CWEB documents.
  dev_url: https://savannah.nongnu.org/projects/chktex

extra:
  recipe-maintainers:
    - bollwyvl
