build_platform:
  osx_arm64: osx_64
  win_arm64: win_64
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
# remove after https://github.com/prefix-dev/rattler-build/issues/1608
remote_ci_setup:
  - conda-forge-ci-setup=4
  - rattler-build=0.40
  - conda-build=25
test: native_and_emulated
